# Copyright 2021 ubuntu
# See LICENSE file for licensing details.

options:
  loglevel:
    default: info
    description: |
      Configures log level. Only supports debug, info, warn, error, panic, or fatal.
    type: string
  metrics:
    default: basic
    description: |
      Set level of detail for exported metrics, specify ‘extensive’ to include server side grpc histogram metrics.
    type: string
